### ISSUE TITLE
upload logo

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-anmmar#4]
So there's 3 of them.. Just use the one where the words "Islamic Personal Finance" are on the bottom.
https://drive.google.com/a/editllc.com/folderview?id=0B88_mCI0OTGkT01HNXlpWF83TjQ&usp=sharing

due:
11-6-15   9p

**Comment by purplyrocky** [comment]
I can't find a good place to insert this logo but it's uploaded and placed in the body as a placeholder. The "anmmar" at the top left isn't an image, it's the site title so I am unable to upload an image there.

**Comment by rodneystrong** [comment]
Did you try editing the theme options to place the logo there?

**Comment by purplyrocky** [comment]
Yes
