### ISSUE TITLE
Copy look of site

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-anmmar#5]
Go to anmmar.editllc.com

Make the site look similar to this site:
http://christianpf.com/

put in placeholder content (text/images) for now

If you need to redo the whole site, go ahead @jperez4509 . I've backed up the current version to anmmar-old.editllc.com, so don't worry about losing anything.

due:
11-12-15   3p

updated due:
12-21-15   5p

**Comment by rodneystrong** [comment]
Just a quick note, if you haven't done this yet, then do it now. Make a child theme of the current theme you're using. 

Do this by going to the "Tools" section and clicking "Child Themes". The instructions from there should help you finish. Be sure you select the correct parent theme. I think right now you're using KnapStack. 

Comment here if you're running into issues.

**Comment by rampage1213** [comment]
Ok so i have fixed the issues that have come into hand! With that being said I will have the Home page and the About page ready to show the client today by 7:00pm and have the full design done next Tuesday. 

Updated due date:
11-24-15 3p

**Comment by rampage1213** [comment]
Anmmar looks great! It can be shown to the client to get feed back for content (there are 2 blog posts that I added already) the only thing that need to be fixed it responsiveness on the front-page and the wordpress navbar button when on iphone/ipad size does not work mostly because bootstrap-js is not loading properly.

**Comment by rodneystrong** [comment]
What is the status of the bootstrap-js issue?

**Comment by rampage1213** [comment]
Added the bootstrap files linked the files in footer.php and its still not working

**Comment by rampage1213** [comment]
Update: I have bootstrap-js linked and working!

**Comment by rodneystrong** [comment]
Good shit dude. 
Gimme a bullet-pointed list of  how you got it to work/what the issue was.

**Comment by rampage1213** [comment]
When working with wordpress sites and linking stylesheets and scripts you have to link all of your files in functions.php like this 
~~~
wp_enqueue_script( 'custom-script', get_stylesheet_directory_uri() . '/js/bootstrap.js', array( 'jquery' ) );
wp_enqueue_script( 'bootstrap-jquery', get_stylesheet_directory_uri() . '/js/jquery.min.js' );
~~~

**Comment by rodneystrong** [comment]
Excellent summary. Thank you sir.

**Comment by rampage1213** [comment]
Commenting here because this is the best place to say this had some issues with a video not embedding right so Richerd pointed out that when using page builder I need to use WordPress text widget and not the siteorigin text widget the reason that the siteorigin  widget does not work is because their widget is created for rich text and not HTML so when adding custom HTML even thought siteorigins widget has an area for HTML input it is better to use the default WordPress widget

**Comment by rodneystrong** [comment]
I'm glad you took the time to detail the issue you had. Unfortunately, you did a subpar job of formatting your explanation; there are *-literally-* no punctuation marks in your previous comment. 

Please resubmit another comment below this one (do not edit the one above) and use formatting tools like bullets points and paragraphs to add clarity and emphasis to your explanation.

**Comment by rampage1213** [comment]
Throughout this project, I have had issues with getting a embedded video to show on the screen of a non-logged in user. What Richard showed me is that the site origin Rich Texted editor even though it has HTML input its mostly for making text look good and that I needed to use the default WordPress text editor.

Things Learned

1. Rich Texted editor 
 * Mostly for text and media with no custom styling

2. Default WordPress Editor 
 * Use for anything HTML 
 * Best for iframe and embeding 

Only things left for this site 
   * Finish blog page
   * Finish sidebar 
   * Get/Add Content

**Comment by rodneystrong** [comment]
Updated due date to 12-21-15  and assigned to @jperez4509

**Comment by rodneystrong** [comment]
If you need to go with a different design for the site, go ahead. But I'll need you to explain your changes. Remember, this is a personal finance blog and the goal for him is to gain email subscribers.

**Comment by jperez4509** [comment]
@rodneystrong: About Page should be done, except for the media queries on mobile. Here is the direct link: http://anmmar.editllc.com/about/

I am going to try to complete all the pages and then do the media queries.

**Comment by rodneystrong** [comment]
Nice job on the parallax sections. Did you use the CSS-only method for those?

**Comment by jperez4509** [comment]
@rodneystrong: No I did not use the CSS-only method, page builder did the parallax affect and then I animated the actual text to fade in up on scroll.

I have also completed the Blog page along with the way post show up. Please let me know if the look works or if you have suggestions or changes. I have attached the direct link: http://anmmar.editllc.com/blog/

As of now I have completed About, Blog, I am going to work on the Get Started page next. Also, please note that the site is still not responsive and I will do that when the site is mostly complete. I am also thinking of changing the font size on the nav after I see how each page is going to look.

**Comment by rodneystrong** [comment]
Blog looks good. Great work. Maybe add a background color to the header (for all pages except the home page) to give a bit more layout/separation from the rest of the page. Maaybe.

**Comment by jperez4509** [comment]
@rodneystrong: I completed the Get Started page. Please let me know if you have any suggestions or sections I should add. I just estimated the sections I thought that would work for the client. Here is the direct link: http://anmmar.editllc.com/start-here/

**Comment by rodneystrong** [comment]
Wow good.. All that's left is the home page now isn't it.. 

The sections are good. Can you link that newsletter sign up box to MailChimp?

**Comment by jperez4509** [comment]
@rodneystrong The plugin does work with MailChimp here is the link to the plugin page https://wordpress.org/plugins/wp-subscribe/

**Comment by jperez4509** [comment]
@rodneystrong: Just finished the home page. I am now working on making the entire site responsive.

**Comment by rodneystrong** [comment]
Perfect; it's looking really good. I'll find out from the client if he's got a mailchimp acct.

**Comment by jperez4509** [comment]
@rodneystrong This site should be completely responsive.
