### ISSUE TITLE
Header help

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-anmmar#6]
Video explaining what I'm trying to do: 

http://somup.com/coXqe4YuZ

We want to show client something by Saturday if possible

**Comment by irms** [comment]
get_header();

pulls in header.php, so in header.php, you would want to do:

```
if( is_home() ) {

// show one header

} else {

// show different header

}
```

`is_home()` is a Wordpress function that figures out if the hierarchy has decided to render the homepage.

https://codex.wordpress.org/Function_Reference/is_home

Does that help?

**Comment by rodneystrong** [comment]
Yes, definitely. Thanks for this. @rampage1213 As you're reading through her documentation, please view these two links as well provided graciously by raquel. 
https://wordpress.org/support/topic/how-to-call-for-an-alternative-header-file

http://codex.wordpress.org/Function_Reference/get_header

**Comment by rampage1213** [comment]
Goal is to get this done today thats for the links

**Comment by rampage1213** [comment]
Thanks*

**Comment by rampage1213** [comment]
This actually didn't work for me 
```
if( is_home() ) {

// show one header

} else {

// show different header

}
```
but this did 
```
if( is_front_page() ) {

// show one header

} else {

// show different header

}
```
