### ISSUE TITLE
Add new blog post #1

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-anmmar#7]
Personal Islamic Finance Defined

The definition of Personal Islamic Finance is - The management of money and financial decisions for a Muslim including budgeting, retirement planning, investing and most importantly - giving.

Simply stated, wants to perfect his religion in all aspects including financial. In order to do this a Muslim's personal financial goal be to die without debt and to maxmize their deeds by giving as much as their wealth away. It is not how much you give but how you give it and to whom that will maxmize your return in the eternal life.&amp;nbsp;&lt;/p&gt;&lt;p&gt;Teaching Muslims how to reach a "0" ZERO sum debt&amp;nbsp;and having the blessing of being able to GIVE is our simple goal. Now to reach zero and get to the point where you can give takes patience, preserverence, determination and faith.&lt;/p&gt;&lt;p&gt;As a Muslim my biggest concern is not how much money I make, but what I do with the money that Allah blesses me with. Every single dollar I spend as a Muslim Allah will ask me about. The issue of personal finance and how I can apply it in a manner that pleases Allah is the reason I created this site.&lt;/p&gt;

If you are looking for a place to learn and apply personal finance with respect to Islam than you have come to the right place. Please leave your comments and remember to sign up for upcoming articles, resources and more.

Purifying Pockets! ~ Anmmar Alsaggaf

due:
11-25-15   10a

**Comment by rampage1213** [comment]
This is posted just fixing up the page its displayed on and designing a Blog page

**Comment by rampage1213** [comment]
Done!
